// Product names and listed prices transcribed from the public DOS price list on 2026-09-24.
// Availability, prescriptions and checkout are not connected to DOS systems.
const catalogProducts = [
  {id:'plain-150-economy',category:'spectacle',group:'plain',name:'1.50 · эконом',price:3000},
  {id:'plain-150-standard',category:'spectacle',group:'plain',name:'1.50 · стандарт',price:8400},
  {id:'anti-156-economy',category:'spectacle',group:'anti',name:'1.56 · эконом',price:5500},
  {id:'anti-150-standard',category:'spectacle',group:'anti',name:'1.50 · стандарт',price:8000},
  {id:'anti-150-premium',category:'spectacle',group:'anti',name:'1.50 · премиум',price:24000},
  {id:'anti-160-standard',category:'spectacle',group:'anti',name:'1.60 · стандарт',price:17000},
  {id:'anti-167-economy',category:'spectacle',group:'anti',name:'1.67 · эконом',price:14000},
  {id:'anti-167-standard',category:'spectacle',group:'anti',name:'1.67 · стандарт',price:23000},
  {id:'anti-167-premium',category:'spectacle',group:'anti',name:'1.67 · премиум',price:68000},
  {id:'anti-174-economy',category:'spectacle',group:'anti',name:'1.74 · эконом',price:23000},
  {id:'anti-174-premium',category:'spectacle',group:'anti',name:'1.74 · премиум',price:136000},
  {id:'computer-156-economy',category:'spectacle',group:'computer',name:'1.56 · эконом',price:9000},
  {id:'computer-150-premium',category:'spectacle',group:'computer',name:'1.50 · премиум',price:44000},
  {id:'photo-156-economy',category:'spectacle',group:'photo',name:'1.56 · эконом',price:8000},
  {id:'photo-156-standard',category:'spectacle',group:'photo',name:'1.56 · стандарт',price:25000},
  {id:'photo-150-premium',category:'spectacle',group:'photo',name:'1.50 · премиум',price:102000},
  {id:'photo-160-premium',category:'spectacle',group:'photo',name:'1.60 · премиум',price:150000},
  {id:'acuvue-oasys-box',category:'contacts',brand:'Johnson & Johnson',name:'Acuvue Oasys',unit:'box',price:15900},
  {id:'acuvue-oasys-ast-box',category:'contacts',brand:'Johnson & Johnson',name:'Acuvue Oasys for AST',unit:'box',price:20000},
  {id:'hydraluxe-box',category:'contacts',brand:'Johnson & Johnson',name:'1-Day Acuvue HydraLuxe',unit:'box',price:18500},
  {id:'biomedics-55-box',category:'contacts',brand:'CooperVision',name:'Biomedics 55',unit:'box',price:13000},
  {id:'biofinity-box',category:'contacts',brand:'CooperVision',name:'Biofinity',unit:'box',price:32400},
  {id:'biofinity-toric-box',category:'contacts',brand:'CooperVision',name:'Biofinity Toric',unit:'box',price:20500},
  {id:'optima-fw-box',category:'contacts',brand:'Bausch & Lomb',name:'Optima FW',unit:'box',price:14000},
  {id:'air-optix-box',category:'contacts',brand:'Alcon',name:'Air Optix HydraGlyde',unit:'box',price:13000},
  {id:'air-optix-ast-box',category:'contacts',brand:'Alcon',name:'Air Optix HydraGlyde for AST',unit:'box',price:17500},
  {id:'acuvue-oasys-pair',category:'contacts',brand:'Johnson & Johnson',name:'Acuvue Oasys',unit:'pair',price:5300},
  {id:'biofinity-pair',category:'contacts',brand:'CooperVision',name:'Biofinity',unit:'pair',price:10800},
  {id:'aqua-soft-120',category:'solutions',brand:'Avizor',name:'Aqua soft, 120 мл',price:3350},
  {id:'aqua-soft-250',category:'solutions',brand:'Avizor',name:'Aqua soft, 250 мл',price:4300},
  {id:'aqua-soft-350',category:'solutions',brand:'Avizor',name:'Aqua soft, 350 мл',price:4600},
  {id:'alvera-100',category:'solutions',brand:'Avizor',name:'Alvera, 100 мл',price:4600},
  {id:'alvera-350',category:'solutions',brand:'Avizor',name:'Alvera, 350 мл',price:6800},
  {id:'unica-sensitive-100',category:'solutions',brand:'Avizor',name:'Unica sensitive, 100 мл',price:3700},
  {id:'unica-sensitive-350',category:'solutions',brand:'Avizor',name:'Unica sensitive, 350 мл',price:5350},
  {id:'comfort-drops-15',category:'drops',brand:'Avizor',name:'Comfort drops, 15 мл',price:3150},
  {id:'moisture-drops-15',category:'drops',brand:'Avizor',name:'Moisture drops, 15 мл',price:5150}
];
