const commerceCopy={
 kk:{menu:'Мәзір',accountEyebrow:'ЖЕКЕ КЕҢІСТІК',accountTitle:'Жеке кабинет',accountIntro:'Өзіңіз туралы деректерді осы браузерде сақтаңыз. Кейін оларды өзгертуге болады.',profileTitle:'Менің деректерім',profileName:'Аты-жөніңіз',profileEmail:'Электрондық пошта',profilePhone:'Телефон (міндетті емес)',profileSave:'Сақтау ↗',localOnly:'Деректер тек осы браузерде сақталады, DOS жүйесіне жіберілмейді.',saved:'Деректер сақталды.',accountNext:'Сізге не керек?',browseShop:'Дүкенді қарау',viewCart:'Себетті ашу',bookExam:'Көруді тексеруге жазылу',cartEyebrow:'СІЗДІҢ ТАҢДАУЫҢЫЗ',cartTitle:'Себет',cartIntro:'Таңдаған тауарларыңызды осы жерден қарап, санын өзгерте аласыз.',cartItemsTitle:'Тауарлар',cartSummary:'Қорытынды',subtotal:'Жалпы сома',cartDisclaimer:'Бұл танысуға арналған прототип. Баға үлгі ретінде берілген, тапсырыс қабылданбайды.',continueShopping:'Тауарларды қарау ↗',askQuestion:'Сұрақ қою',addCart:'Себетке қосу',added:'Қосылды ✓',empty:'Себет әзірге бос.',remove:'Өшіру',quantity:'Саны',items:{contacts:'Acuvue Oasys · үлгі',lenses:'Шағылысуға қарсы линза · үлгі',care:'Aqua soft 120 мл · үлгі'}},
 ru:{menu:'Меню',accountEyebrow:'ЛИЧНОЕ ПРОСТРАНСТВО',accountTitle:'Личный кабинет',accountIntro:'Сохраните свои данные в этом браузере. Их можно изменить позже.',profileTitle:'Мои данные',profileName:'Имя и фамилия',profileEmail:'Электронная почта',profilePhone:'Телефон (необязательно)',profileSave:'Сохранить ↗',localOnly:'Данные хранятся только в этом браузере и не отправляются в DOS.',saved:'Данные сохранены.',accountNext:'Что вам нужно?',browseShop:'Посмотреть магазин',viewCart:'Открыть корзину',bookExam:'Записаться на проверку зрения',cartEyebrow:'ВАШ ВЫБОР',cartTitle:'Корзина',cartIntro:'Просмотрите товары и измените количество.',cartItemsTitle:'Товары',cartSummary:'Итого',subtotal:'Общая сумма',cartDisclaimer:'Это демонстрационный прототип. Цены приведены для примера, заказы не принимаются.',continueShopping:'Посмотреть товары ↗',askQuestion:'Задать вопрос',addCart:'В корзину',added:'Добавлено ✓',empty:'Корзина пока пуста.',remove:'Удалить',quantity:'Количество',items:{contacts:'Acuvue Oasys · пример',lenses:'Антибликовые линзы · пример',care:'Aqua soft 120 мл · пример'}},
 en:{menu:'Menu',accountEyebrow:'YOUR SPACE',accountTitle:'My account',accountIntro:'Save your details in this browser. You can change them later.',profileTitle:'My details',profileName:'Full name',profileEmail:'Email',profilePhone:'Phone (optional)',profileSave:'Save ↗',localOnly:'Details stay in this browser and are not sent to DOS.',saved:'Details saved.',accountNext:'What would you like to do?',browseShop:'Browse shop',viewCart:'View cart',bookExam:'Book an eye exam',cartEyebrow:'YOUR SELECTION',cartTitle:'Cart',cartIntro:'Review your items and change quantities.',cartItemsTitle:'Items',cartSummary:'Summary',subtotal:'Subtotal',cartDisclaimer:'This is a concept prototype. Prices are examples and orders are not accepted.',continueShopping:'Browse products ↗',askQuestion:'Ask a question',addCart:'Add to cart',added:'Added ✓',empty:'Your cart is empty.',remove:'Remove',quantity:'Quantity',items:{contacts:'Acuvue Oasys · example',lenses:'Anti-reflective lenses · example',care:'Aqua soft 120 ml · example'}}
};
const catalogCopy={
 kk:{catalogEyebrow:'БАРЛЫҚ ӨНІМ БІР ЖЕРДЕ',catalogTitle:'Көзілдірік пен линзалар.',catalogIntro:'Көзілдірік линзалары, жанаспалы линзалар, ерітінділер мен тамшылар. Атауын немесе брендін жазып, керегін табыңыз.',positions:'позиция',categories:'санат',sortLabel:'Реттеу',sortDefault:'Прайс ретімен',sortLow:'Баға: арзандан',sortHigh:'Баға: қымбаттан',filterAll:'Барлығы',filterSpectacle:'Көзілдірік линзалары',filterContacts:'Жанаспалы линзалар',filterSolutions:'Ерітінділер',filterDrops:'Тамшылар',search:'Өнімді іздеу',shown:n=>`${n} позиция көрсетілді`,noResults:'Ештеңе табылмады. Басқа атау жазып көріңіз.',catalogDisclaimer:'Бағалар DOS ашық прайсынан алынған (24.09.2026). Бар-жоғын және рецептіңізге сәйкестігін маманнан нақтылаңыз. Бұл прототипте тапсырыс жіберілмейді.',groups:{plain:'Қаптамасыз',anti:'Шағылысуға қарсы',computer:'Компьютерге арналған',photo:'Фотохромды'},units:{box:'қаптама',pair:'жұп'}},
 ru:{catalogEyebrow:'ВСЕ ТОВАРЫ В ОДНОМ МЕСТЕ',catalogTitle:'Очки и линзы.',catalogIntro:'Очковые и контактные линзы, растворы и капли. Найдите нужное по названию или бренду.',positions:'позиций',categories:'категории',sortLabel:'Сортировка',sortDefault:'По прайсу',sortLow:'Цена: по возрастанию',sortHigh:'Цена: по убыванию',filterAll:'Все',filterSpectacle:'Очковые линзы',filterContacts:'Контактные линзы',filterSolutions:'Растворы',filterDrops:'Капли',search:'Поиск товара',shown:n=>`Показано ${n} позиций`,noResults:'Ничего не найдено. Попробуйте другое название.',catalogDisclaimer:'Цены взяты из открытого прайса DOS (24.09.2026). Наличие и соответствие рецепту уточняйте у специалиста. Этот прототип не принимает заказы.',groups:{plain:'Без покрытия',anti:'Антибликовые',computer:'Компьютерные',photo:'Фотохромные'},units:{box:'упаковка',pair:'пара'}},
 en:{catalogEyebrow:'EVERY ITEM IN ONE PLACE',catalogTitle:'Eyewear and lenses.',catalogIntro:'Spectacle and contact lenses, solutions and drops. Search by product name or brand.',positions:'items',categories:'categories',sortLabel:'Sort',sortDefault:'Price list order',sortLow:'Price: low to high',sortHigh:'Price: high to low',filterAll:'All',filterSpectacle:'Spectacle lenses',filterContacts:'Contact lenses',filterSolutions:'Solutions',filterDrops:'Drops',search:'Search products',shown:n=>`${n} items shown`,noResults:'No products found. Try another search.',catalogDisclaimer:'Prices are from the public DOS price list (24 Sep 2026). Confirm stock and prescription suitability with a specialist. This prototype does not submit orders.',groups:{plain:'Uncoated',anti:'Anti-reflective',computer:'Computer lenses',photo:'Photochromic'},units:{box:'box',pair:'pair'}}
};
for(const lang of Object.keys(catalogCopy))Object.assign(commerceCopy[lang],catalogCopy[lang]);
commerceCopy.kk.cartDisclaimer='Бағалар DOS ашық прайсынан алынған (24.09.2026). Тапсырыс бұл прототипте жіберілмейді.';
commerceCopy.ru.cartDisclaimer='Цены взяты из открытого прайса DOS (24.09.2026). Заказ в этом прототипе не отправляется.';
commerceCopy.en.cartDisclaimer='Prices are from the public DOS price list (24 Sep 2026). This prototype does not submit orders.';
const commerceKey='dos-prototype-cart';
const legacyIds={contacts:'acuvue-oasys-box',lenses:'anti-156-economy',care:'aqua-soft-120'};
const productById=Object.fromEntries(catalogProducts.map(item=>[item.id,item]));
function commerceLang(){return commerceCopy[document.documentElement.lang]||commerceCopy.kk}
function readCart(){try{const data=JSON.parse(localStorage.getItem(commerceKey)||'{}');const cart={};for(const [rawId,rawQuantity] of Object.entries(data)){const id=legacyIds[rawId]||rawId;if(productById[id])cart[id]=Math.min(99,(cart[id]||0)+Math.max(0,parseInt(rawQuantity,10)||0))}return cart}catch{return {}}}
function saveCart(cart){try{localStorage.setItem(commerceKey,JSON.stringify(cart))}catch{}}
function formatPrice(value){return new Intl.NumberFormat(document.documentElement.lang==='kk'?'kk-KZ':'ru-RU').format(value)+' ₸'}
function productName(item,c=commerceLang()){return item.category==='spectacle'?`${c.groups[item.group]} · ${item.name}`:item.name}
function productMeta(item,c=commerceLang()){return item.category==='spectacle'?c.units.pair:item.category==='contacts'?`${item.brand} · ${c.units[item.unit]}`:item.brand}
function renderCart(){const target=document.querySelector('#cartItems');if(!target)return;const c=commerceLang(),cart=readCart();const ids=catalogProducts.map(p=>p.id).filter(id=>cart[id]>0);target.replaceChildren();if(!ids.length){const p=document.createElement('p');p.className='cart-empty';p.textContent=c.empty;target.append(p)}for(const id of ids){const item=productById[id],row=document.createElement('div');row.className='cart-row';const info=document.createElement('div');const title=document.createElement('h3');title.textContent=productName(item,c);const meta=document.createElement('p');meta.textContent=`${productMeta(item,c)} · ${formatPrice(item.price)}`;info.append(title,meta);const controls=document.createElement('div');controls.className='cart-controls';const minus=document.createElement('button');minus.type='button';minus.textContent='−';minus.setAttribute('aria-label',`${c.quantity}: ${productName(item,c)} −`);const qty=document.createElement('span');qty.textContent=cart[id];const plus=document.createElement('button');plus.type='button';plus.textContent='+';plus.setAttribute('aria-label',`${c.quantity}: ${productName(item,c)} +`);const remove=document.createElement('button');remove.type='button';remove.className='cart-remove';remove.textContent=c.remove;minus.onclick=()=>changeQuantity(id,-1);plus.onclick=()=>changeQuantity(id,1);remove.onclick=()=>changeQuantity(id,-cart[id]);controls.append(minus,qty,plus,remove);row.append(info,controls);target.append(row)}document.querySelector('#cartTotal').textContent=formatPrice(ids.reduce((sum,id)=>sum+cart[id]*productById[id].price,0))}
function changeQuantity(id,delta){if(!productById[id])return;const cart=readCart();cart[id]=Math.max(0,Math.min(99,(cart[id]||0)+delta));if(!cart[id])delete cart[id];saveCart(cart);renderCart();updateCartBadge()}
function updateCartBadge(){const count=Object.values(readCart()).reduce((a,b)=>a+b,0);document.querySelectorAll('.header-cart').forEach(link=>{let badge=link.querySelector('.cart-badge');if(!badge){badge=document.createElement('span');badge.className='cart-badge';link.append(badge)}badge.textContent=count;badge.hidden=!count})}
function renderCatalog(){const grid=document.querySelector('#catalogGrid');if(!grid)return;const c=commerceLang(),query=document.querySelector('#catalogSearch').value.trim().toLocaleLowerCase(),category=document.querySelector('.catalog-filters [aria-pressed="true"]')?.dataset.category||'all',sort=document.querySelector('#catalogSort').value;let items=catalogProducts.filter(item=>(category==='all'||item.category===category)&&`${productName(item,c)} ${item.brand||''} ${productMeta(item,c)}`.toLocaleLowerCase().includes(query));if(sort==='price-asc')items.sort((a,b)=>a.price-b.price);if(sort==='price-desc')items.sort((a,b)=>b.price-a.price);document.querySelector('#catalogCount').textContent=c.shown(items.length);grid.replaceChildren();if(!items.length){const empty=document.createElement('p');empty.className='catalog-empty';empty.textContent=c.noResults;grid.append(empty)}items.forEach((item,index)=>{const card=document.createElement('article');card.className='catalog-card';const top=document.createElement('div');top.className='catalog-card-top';const symbol=document.createElement('span');symbol.className='catalog-symbol';symbol.textContent={spectacle:'◉',contacts:'◎',solutions:'◇',drops:'◈'}[item.category];symbol.setAttribute('aria-hidden','true');const no=document.createElement('span');no.textContent=String(catalogProducts.indexOf(item)+1).padStart(2,'0');top.append(symbol,no);const cat=document.createElement('div');cat.className='catalog-category';cat.textContent=c[{spectacle:'filterSpectacle',contacts:'filterContacts',solutions:'filterSolutions',drops:'filterDrops'}[item.category]];const title=document.createElement('h3');title.textContent=productName(item,c);const meta=document.createElement('p');meta.textContent=productMeta(item,c);const bottom=document.createElement('div');bottom.className='catalog-card-bottom';const price=document.createElement('strong');price.textContent=formatPrice(item.price);const add=document.createElement('button');add.type='button';add.className='catalog-add';add.textContent=c.addCart;add.setAttribute('aria-label',`${productName(item,c)} — ${c.addCart}`);add.onclick=()=>{changeQuantity(item.id,1);add.textContent=c.added;setTimeout(()=>{if(add.isConnected)add.textContent=commerceLang().addCart},1500)};bottom.append(price,add);card.append(top,cat,title,meta,bottom);grid.append(card)})}
function updateCommerceLanguage(){const c=commerceLang();document.querySelectorAll('[data-c]').forEach(el=>{el.textContent=c[el.dataset.c]||''});const toggle=document.querySelector('.menu-toggle');if(toggle){toggle.querySelector('[data-ui="menu"]').textContent=c.menu;toggle.setAttribute('aria-label',c.menu)}document.querySelector('.header-account')?.setAttribute('aria-label',c.accountTitle);document.querySelector('.header-cart')?.setAttribute('aria-label',c.cartTitle);const search=document.querySelector('#catalogSearch');if(search){search.placeholder=c.search;search.setAttribute('aria-label',c.search)}renderCatalog();renderCart();updateCartBadge()}
document.addEventListener('DOMContentLoaded',()=>{const toggle=document.querySelector('.menu-toggle');if(toggle){toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));document.querySelector('#main-nav').classList.toggle('is-open',!open)});document.querySelectorAll('#main-nav a').forEach(link=>link.addEventListener('click',()=>{toggle.setAttribute('aria-expanded','false');document.querySelector('#main-nav').classList.remove('is-open')}))}document.querySelector('#catalogSearch')?.addEventListener('input',renderCatalog);document.querySelector('#catalogSort')?.addEventListener('change',renderCatalog);document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-category]').forEach(other=>other.setAttribute('aria-pressed',String(other===button)));renderCatalog()}));const profile=document.querySelector('#profileForm');if(profile){try{const data=JSON.parse(localStorage.getItem('dos-prototype-profile')||'{}');for(const key of ['name','email','phone'])profile.elements[key].value=data[key]||''}catch{}profile.addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(profile));try{localStorage.setItem('dos-prototype-profile',JSON.stringify(data));document.querySelector('#profileStatus').textContent=commerceLang().saved}catch{document.querySelector('#profileStatus').textContent=commerceLang().localOnly}})}document.addEventListener('dos:language',updateCommerceLanguage);updateCommerceLanguage()});
Object.assign(commerceCopy.kk,{guidePromoEyebrow:'ЛИНЗАНЫ ҚОЛДАНУ',guidePromoTitle:'Линзаны дұрыс тағу және шешу',guidePromoText:'Қадамдық нұсқаулық пен күнделікті күтім ережелері'});
Object.assign(commerceCopy.ru,{guidePromoEyebrow:'КАК НОСИТЬ ЛИНЗЫ',guidePromoTitle:'Как надевать и снимать линзы',guidePromoText:'Пошаговая инструкция и правила ухода'});
Object.assign(commerceCopy.en,{guidePromoEyebrow:'USING CONTACT LENSES',guidePromoTitle:'How to insert and remove lenses',guidePromoText:'Step-by-step guidance and daily care tips'});
